In [4]:
import pandas as pd
import os
def combine(file1,file2):
    data1=pd.read_excel(file1)
    data2 = pd.read_excel(file2)
    data=pd.merge(data1,data2,on="LSOA code")
    return data
path=r"..\..\result"
file1=os.path.join(path,"kmeans_result_predict.xlsx")
file2=os.path.join(path,"predict.xlsx")
data=combine(file1,file2)
data

,LSOA code,final score,final_label,Longitude,Latitude,crime_score_x,poor_score,health_score,environment_score,retail_score,air_label,crime_score_y
0,E01000668,1.00020,excellent,0.039747,51.391979,excellent,excellent,excellent,excellent,excellent,excellent,excellent
1,E01000669,1.00020,excellent,0.039378,51.389827,excellent,excellent,excellent,excellent,excellent,excellent,excellent
2,E01001093,1.00020,excellent,-0.111658,51.344085,excellent,excellent,excellent,excellent,excellent,excellent,excellent
3,E01002166,1.00020,excellent,-0.292872,51.593097,excellent,excellent,excellent,excellent,excellent,excellent,excellent
4,E01004119,1.00020,excellent,-0.226173,51.371505,excellent,excellent,excellent,excellent,excellent,excellent,excellent
...,...,...,...,...,...,...,...,...,...,...,...,...
4826,E01033587,0.19420,poor,0.078423,51.533188,good,average,good,average,good,good,good
4827,E01001667,0.16270,poor,0.008729,51.488117,good,average,good,average,good,average,good
4828,E01003482,0.09445,poor,0.065260,51.515696,good,good,average,average,average,good,good
4829,E01000092,0.08000,poor,0.096822,51.521269,good,average,average,average,good,good,good
4830,E01002444,0.06295,poor,-0.453155,51.470876,good,good,average,average,average,average,good

In [ ]:
data.to_excel(os.path.join(path,"kmeans_result_prediction.xlsx"))