In [2]:
import pandas as pd
import numpy as np
import os
path="..\..\dataset\screened_crime"
def get_location(path):
    location=pd.DataFrame(columns=["LSOA code","Longitude","Latitude"])
    location.set_index("LSOA code",inplace=True)

    for dirpath, dirnames, filenames in os.walk(path):
        for filename in filenames:
            crime_data=pd.read_excel(os.path.join(dirpath, filename))
            crime_data.set_index("LSOA code",inplace=True)
            for i, row in crime_data.iterrows():
                if i not in location.index:
                    location.loc[i]=[row["Longitude"],row["Latitude"]]


    return location
location=get_location(path)

location

           Longitude   Latitude
LSOA code
E01000027   0.140035  51.589112
E01000028   0.129344  51.583695
E01000029   0.133206  51.579543
E01000030   0.133602  51.586154
E01000031   0.137827  51.575601
...              ...        ...
E01003679   0.053427  51.590975
E01004157  -0.210298  51.360058
E01004154  -0.177653  51.354177
E01000826  -0.001814  51.396805
E01033575   0.021138  51.509100

[4831 rows x 2 columns]

In [ ]:
location.to_excel(r"..\..\dataset\LSOA_code.xlsx")